# Generated by Django 4.2.7 on 2023-12-14 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photo_booths', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('main_thumbnail_image_url', models.URLField(max_length=512)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('is_public', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hashtag', models.ManyToManyField(related_name='events', to='photo_booths.hashtag')),
                ('photo_booth_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='photo_booths.photoboothbrand')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='UserEventLikeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'user event like log',
                'verbose_name_plural': 'user event like logs',
                'db_table': 'user_event_like_log',
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_image_url', models.URLField(max_length=512)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_image', to='events.event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'event image',
                'verbose_name_plural': 'event images',
                'db_table': 'event_image',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='user_event_like_logs',
            field=models.ManyToManyField(related_name='event_like_logs', through='events.UserEventLikeLog', to=settings.AUTH_USER_MODEL),
        ),
    ]
