# Generated by Django 4.2.7 on 2023-12-13 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEventLikeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user event like log',
                'verbose_name_plural': 'user event like logs',
                'db_table': 'user_event_like_log',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='user_event_like_logs',
            field=models.ManyToManyField(related_name='event_like_logs', through='events.UserEventLikeLog', to=settings.AUTH_USER_MODEL),
        ),
    ]
