# Generated by Django 4.2.7 on 2023-12-13 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo_booths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoboothbrandimage',
            name='photo_booth_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_booth_brand_image', to='photo_booths.photoboothbrand'),
        ),
    ]
